name: "Import patches"
description: "Import patches into upstream"
runs:
    using: "composite"
    steps:
        - name: Import patches
          shell: bash
          run: |
              ./melon import --minimal
