name: "Download upstream repository"
description: "Download Firefox repository"
runs:
    using: "composite"
    steps:
        - name: Download upstream repository
          shell: bash
          run: |
              ./melon download
