name: "Setup Git"
description: "Setup the Git environment"
runs:
    using: "composite"
    steps:
        - name: Setup Git
          shell: bash
          run: |
              git config --global user.email "72629236+dothq-robot@users.noreply.github.com"
              git config --global user.name "dothq-robot"
