name: "Package"
description: "Package the browser into a nice little package"
inputs:
    target:
        description: "Build target"
        required: true
runs:
    using: "composite"
    steps:
        - name: Package
          shell: bash
          run: PYTHONPATH=.github/actions python3 ./.github/actions/package/${{ inputs.target }}.py
