name: Enforce code style

on:
    push:
        paths:
            - "build/**"
            - "scripts/**"
    workflow_dispatch:

jobs:
    prettier:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              run: |
                  git clone https://${{ secrets.ROBOT_TOKEN }}@github.com/dothq/browser-desktop.git -b ${GITHUB_REF#refs/heads/}
                  cd browser-desktop
                  git status

            - name: Setup Git
              run: |
                  git config --global user.name "dothq-robot"
                  git config --global user.email "72629236+dothq-robot@users.noreply.github.com"

            - name: Install dependencies
              run: cd browser-desktop && yarn

            - name: Format
              run: cd browser-desktop && git pull && yarn prettier

            - name: Push to GitHub
              run: |
                  cd browser-desktop
                  git status
                  git add . 2>&1 || true
                  git commit -m "🎨 Enforce code style" 2>&1 || true
                  git push origin ${GITHUB_REF#refs/heads/} 2>&1 || true
